# Generated by Django 3.2.9 on 2021-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fields',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
