# Generated by Django 3.2.9 on 2021-12-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdetails', '0002_client_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fields',
            new_name='isclaimed',
        ),
    ]
