# Generated by Django 3.2.9 on 2021-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdetails', '0003_rename_fields_client_isclaimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='claimedby',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
